In [1]:
#negetive slicing
#slice from the index 3 from the end to index 1 from the end
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [7]:
#use the step value to determine step of slicing
#Return every other element from index 1 to 5
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [11]:
#return every other element
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [19]:
#slicing 2D arrays
#from the second element ,slice elements from index 0 to index 4(not included)
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,0:4])

[6 7 8 9]


In [23]:
#from both elements ,return to index 2
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [25]:
#from both elements,slice index 1 to index 4,this will return 2D arrays
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [27]:
#checking the data type of array
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.dtype)

int32


In [29]:
#get the data type of array containing string
import numpy as np
arr=np.array(["thar","BMW","Bullet"])
print(arr.dtype)

<U6


In [37]:
#create an array with data type string 
import numpy as np
arr=np.array([1,2,3,4],dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [41]:
#create an array with data type 4 byte integer
import numpy as np
arr=np.array([1,2,3,4],dtype="i4")
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [43]:
# change the data type from float to integer by using"i"as parameter value
import numpy as np
arr=np.array([1.1,1.2,1.3])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 1 1]
int32


In [45]:
#chnge data type integer to boolean
import numpy as np
arr=np.array([1,2,3,4])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True  True  True]
bool


In [47]:
#make a copy,change the original array ,display both arrays
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=16
print(arr)
print(x)

[16  2  3  4  5]
[1 2 3 4 5]


In [49]:
#make a view ,change the original array,display both arrays
import numpy as np
arr=np.array([1,2,3,4])
x=arr.view()
arr[1]=10
print(arr)
print(x)

[ 1 10  3  4]
[ 1 10  3  4]
