In [ ]:
#NumPy Libarary
#Explaination-
#NumPy is a python library.NumPy is used for working with arrays.NumPy is short for "Numerical Python".

In [1]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [12]:
import numpy as np
print(np.__version__)

1.26.4


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
# O D array
import numpy as np
arr=np.array(6)
print(arr)

6


In [20]:
#1D array
import numpy as np
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [24]:
#2D array
import numpy as np
arr=np.array([[1,2,3],[5,6,7]])
print(arr)

[[1 2 3]
 [5 6 7]]


In [26]:
#3D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
#check number of dimension
import numpy as np
x=np.array(13)
y=np.array([1,2,3])
z=np.array([[1,2,3],[4,5,6]])
w=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[1,2,3]]])
print(x.ndim)
print(y.ndim)
print(z.ndim)
print(w.ndim)

0
1
2
3


In [58]:
#Higher dimensional array
import numpy as np
arr=np.array([1,2,3],ndmin=7)
print(arr)
print("Number of dimension:",arr.ndim)

[[[[[[[1 2 3]]]]]]]
Number of dimension: 7


In [70]:
#access array elemnts
import numpy as np
arr=np.array([2,5,1,4,5,9,7])
print(arr[5])

9


In [72]:
#get third and fourth element of array and add them
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2]+arr[4])

8


In [76]:
#access 2D arrays 
import numpy as np
arr=np.array([[1,2,3,5,4,5],[7,6,9,3,2,5]])
print("Fifth element second rows:",arr[1][3])

Fifth element second rows: 3


In [5]:
#access 3D arrays
#access third element of second array of the first array
import numpy as np
arr=np.array([[[2,8,4,9,1],[1,7,7,9,2]],[[1,2,3,4,5],[9,8,6,4,1]]])
print(arr[0][1][2])

7


In [9]:
#negetive indexing
#print last element of second dimension 
import numpy as np
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,13]])
print(" last element of second dimension:",arr[1,-1])

 last element of second dimension: 13


In [11]:
#slicing arrays
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[1:5])

[2 3 4 5]


In [15]:
#slice elements from index 4 to the end of array
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[4:])

[5 6 7 8 9]


In [17]:
#slice elements from begining to the index 5 (not included)
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print([:5])

SyntaxError: invalid syntax (1497895832.py, line 4)